In [110]:
# Paqueteria
import pandas as pd

In [127]:
# Lectura de CSV
csv_horas_bus = "Data/horas_buses_peru.xlsx"
csv_horas_vuelo = "Data/peruvian_departments_flight_times_with_coords.csv"
csv_lat_long = "Data/peruvian_departments_travel_times_with_coords.csv"

In [116]:
df_horas_bus_total = pd.read_excel(csv_horas_bus)
df_horas_vuelo = pd.read_csv(csv_horas_vuelo)
df_lat_long = pd.read_csv(csv_lat_long)

In [117]:

df_horas_bus_total

,Departamento,Capital,Chachapoyas,Huaraz,Abancay,Arequipa,Ayacucho,Cajamarca,Cusco,Huancavelica,...,Lima,Puerto Maldonado,Moquegua,Cerro de Pasco,Piura,Puno,Moyobamba,Tacna,Tumbes,Pucallpa
0,Amazonas,Chachapoyas,0,19,37,38,31,9,41,29,...,21,50,39,22,10,43,21,21,16,21
1,Áncash,Huaraz,19,0,23,24,17,12,27,14,...,6,36,7,10,13,29,7,27,18,17
2,Apurímac,Abancay,37,23,0,13,8,30,5,12,...,15,14,15,18,31,11,15,18,36,27
3,Arequipa,Arequipa,38,24,13,0,18,31,9,18,...,16,13,3,20,32,5,16,5,37,32
4,Ayacucho,Ayacucho,31,17,8,0,0,24,12,5,...,9,21,9,10,25,18,9,19,30,19
5,Cajamarca,Cajamarca,9,12,30,31,24,0,34,22,...,15,43,33,18,9,37,14,34,13,27
6,Cusco,Cusco,41,27,5,9,12,34,0,17,...,20,9,11,22,36,7,20,13,40,29
7,Huancavelica,Huancavelica,29,14,12,18,5,22,17,0,...,7,26,19,8,24,23,7,21,28,17
8,Huánuco,Huánuco,19,8,20,23,13,20,25,9,...,8,35,7,3,20,29,7,26,25,8
9,Ica,Ica,26,11,11,12,7,19,15,6,...,4,25,13,10,20,17,26,15,25,20
10,Junín,Huancayo,26,14,14,21,6,22,18,3,...,7,28,22,4,23,25,20,23,28,12
11,La Libertad,Trujillo,12,6,24,25,18,6,29,16,...,9,38,27,12,7,30,16,28,12,22
12,Lambayeque,Chiclayo,9,10,28,29,22,5,33,20,...,13,42,31,16,3,35,11,32,8,37
13,Lima,Lima,21,6,15,16,9,15,20,7,...,0,29,17,4,15,21,21,19,20,15
14,Madre de Dios,Puerto Maldonado,50,36,14,13,21,43,9,26,...,29,0,14,31,44,10,29,16,49,37
15,Moquegua,Moquegua,39,7,15,3,9,33,11,19,...,17,14,0,22,34,4,17,2,38,33
16,Pasco,Cerro de Pasco,22,10,18,20,10,18,22,8,...,4,31,22,0,19,26,17,24,23,11
17,Piura,Piura,10,13,31,32,25,9,36,24,...,15,44,34,19,0,39,12,36,5,29
18,Puno,Puno,43,29,11,5,18,37,7,23,...,21,10,4,26,39,0,21,6,42,34
19,San Martín,Moyobamba,21,7,15,16,9,14,20,7,...,21,29,17,17,12,21,0,19,20,15
20,Tacna,Tacna,21,27,18,5,19,34,13,21,...,19,16,2,24,36,6,19,0,39,35
21,Tumbes,Tumbes,16,18,36,37,30,13,40,28,...,20,49,38,23,5,42,20,39,0,34
22,Ucayali,Pucallpa,21,17,27,32,19,27,29,17,...,15,37,33,11,29,34,15,35,34,0

# HORAS VIA TERRESTE

In [125]:
from statistics import median
department_counts = {}
dis_horas_centro_min = 10
dis_horas_centro_inter = 18
dis_horas_centro_max = 30 
lst =[]

for i in range(0, 23):
    row_str = df_horas_bus.iloc[i]
    department = row_str.name
    row_int = [int(item) if item.isdigit() else item for item in row_str]
    row_int_filtered = [int(item) for item in row_int if isinstance(item, int) or (isinstance(item, str) and item.isdigit())]
    if row_int_filtered:
        min_value = __builtins__.min(row_int_filtered)
        max_value = __builtins__.max(row_int_filtered)
        sortedvalue = sorted(row_int_filtered)
        second_min_value = sortedvalue[1]
        median_value = median (row_int_filtered)
        count_greater_than_min = sum(1 for item in row_int if isinstance(item, int) and item < dis_horas_centro_min)
        count_greater_than_inter = sum(1 for item in row_int if isinstance(item, int) and item > dis_horas_centro_min and item <dis_horas_centro_inter)
        count_greater_than_max = sum(1 for item in row_int if isinstance(item, int) and item > dis_horas_centro_inter and item <dis_horas_centro_max)
        new_row = [min_value, second_min_value, max_value, median_value, count_greater_than_min,count_greater_than_inter,count_greater_than_max]
        department_counts[department] = [ median_value,min_value, max_value, count_greater_than_min,count_greater_than_inter,count_greater_than_max, second_min_value]
        lst.append(new_row)
sorted_departments = sorted(department_counts.items(), key=lambda item: item[0][2], reverse=True)
department_data = []
for department, counts in sorted_departments:
    department_data.append({
        'Department': department,
        'Min Value': counts[1],
        'Second Min Value': counts[6],
        'Max Value': counts[2],
        'Median Value': counts[0],
        'Count < 10hrs': counts[3],
        'Count < 18hrs': counts[4],
        'Count < 30hrs': counts[5]
    })
    
df = pd.DataFrame(department_data)
sorted_df = df.sort_values(by='Median Value')
sorted_df

,Department,Min Value,Second Min Value,Max Value,Median Value,Count < 10hrs,Count < 18hrs,Count < 30hrs
21,La Libertad,0,1,29,9.5,9,3,5
20,Ica,0,1,26,10.0,5,2,5
6,Junín,0,2,28,10.5,7,5,3
16,Amazonas,0,2,27,11.0,9,7,4
15,Ancash,0,1,29,11.0,7,3,5
14,Madre de Dios,0,1,29,11.5,4,9,4
7,Puno,0,2,29,11.5,6,5,3
0,Apurimac,0,1,29,13.0,6,4,5
4,Loreto,0,3,29,13.5,5,7,6
12,Cajamarca,0,2,29,13.5,6,3,6
8,San Martín,0,1,29,14.0,6,5,8
11,Callao,0,4,28,14.0,3,4,3
13,Arequipa,0,7,29,14.0,6,3,7
2,Cusco,0,5,29,14.0,5,6,6
18,Huancavelica,0,1,28,14.0,6,3,7
5,Moquegua,0,1,29,15.0,6,6,9
10,Lima,0,1,25,15.5,7,8,7
17,Ayacucho,0,6,27,16.0,7,4,8
19,Huanuco,0,1,29,16.0,5,4,7
1,Piura,0,2,29,17.0,4,5,7
9,Lambayeque,0,2,28,18.5,7,2,9
3,Pasco,0,1,29,18.5,5,1,8

In [6]:
row_str = df_horas_bus.iloc[0]
row_amazonas =  df_horas_bus.iloc[1]
tuple_data_from_amazonas = list(zip(row_str,row_amazonas ))
filtered_tuples = [t for t in tuple_data_from_amazonas if 'No Info' not in t]
print(filtered_tuples)
min_horas = 4
max_horas = 10

[('Amazonas', '0'), ('Ancash', '14'), ('Ayacucho', '8'), ('Cajamarca', '12'), ('Callao', '27'), ('Cusco', '21'), ('Huancavelica', '4'), ('Huanuco', '11'), ('Ica', '8'), ('Junín', '2'), ('La Libertad', '4'), ('Lambayeque', '5'), ('Lima', '20'), ('Loreto', '3'), ('Madre de Dios', '15'), ('Moquegua', '5'), ('Pasco', '16'), ('Piura', '15'), ('Puno', '14'), ('San Martín', '10'), ('Tumbes', '23'), ('Latitude', '-5.06929'), ('Longitude', '-78.0569')]

In [7]:
def find_divisors(n):
    divisors = []
    for i in range(2, n):  # Start from 2 and go up to n-1
        if n % i == 0:
            divisors.append(i)
    return divisors

# Example usage
number = 2
divisors = find_divisors(number)
divisors

[]

In [8]:
def find_divisors_with_condition(n):
    divisors = [i for i in range(2, n) if n % i == 0]

    # Check if there are exactly two divisors
    if len(divisors) == 1:
        # Return the divisors and the greater one
        return n
    else:
        return divisors, None

# Example usage
number = 2
divisors, greatest_divisor = find_divisors_with_condition(number)

if greatest_divisor:
    print(f"The divisors of {number} are {divisors}, and the greatest divisor is {greatest_divisor}.")
else:
    print(f"The divisors of {number} are {divisors}.")

The divisors of 2 are [].